Some refreshments (#16)
* Update dependencies to latest versions. (except for tui).
* Switch to Rust 2018 edition.
* Update path syntax to 2018 edition.
* structopt: remove raw attributes.

  See https://github.com/TeXitoi/structopt/blob/master/CHANGELOG.md#raw-attributes-are-removed-198-by-sphynx

* Add "quote" to dependencies.
  Solves:
  ```
  error[E0433]: failed to resolve: could not find `__rt` in `quote`
     --> /home/ngirard/.cargo/registry/src/github.com-1ecc6299db9ec823/failure_derive-0.1.6/src/lib.rs:107:70
      |
  107 | fn display_body(s: &synstructure::Structure) -> Result<Option<quote::__rt::TokenStream>, Error> {
      |                                                                      ^^^^ could not find `__rt` in `quote`
  ```

  See https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html

* 2018 Edition: drop superfluous 'extern crate'.
* Use CommandExt.pre_exec() instead of deprecated before_exec()

  See https://doc.rust-lang.org/nightly/std/os/unix/process/trait.CommandExt.html